<?php

declare(strict_types=1);

namespace Semitexa\Testing\Console\Command;

use Semitexa\Core\Attributes\AsCommand;
use Semitexa\Core\Console\Command\BaseCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;

#[AsCommand(name: 'test:init', description: 'Scaffold the universal payload contract test into the project')]
class TestInitCommand extends BaseCommand
{
    protected function configure(): void
    {
        $this->setName('test:init')
            ->setDescription('Scaffold the universal payload contract test into the project');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        $io = new SymfonyStyle($input, $output);
        $projectRoot = $this->getProjectRoot();

        $targetDir = $projectRoot . '/tests/Payload';
        $targetFile = $targetDir . '/ProjectPayloadsContractTest.php';

        if (file_exists($targetFile)) {
            $io->warning('File already exists: tests/Payload/ProjectPayloadsContractTest.php');
            $io->text('Delete it manually if you want to re-scaffold.');
            return Command::SUCCESS;
        }

        if (!is_dir($targetDir) && !mkdir($targetDir, 0755, true)) {
            $io->error("Cannot create directory: {$targetDir}");
            return Command::FAILURE;
        }

        if (file_put_contents($targetFile, self::STUB) === false) {
            $io->error("Failed to write file: {$targetFile}");
            return Command::FAILURE;
        }

        $io->success('Created tests/Payload/ProjectPayloadsContractTest.php');
        $io->text([
            'This test auto-discovers all PayloadDTO classes with #[TestablePayload]',
            'and runs their declared strategies via @dataProvider.',
            '',
            'Run it:  bin/semitexa test:run -- --filter ProjectPayloadsContractTest',
        ]);

        return Command::SUCCESS;
    }

    private const STUB = <<<'PHP'
<?php

declare(strict_types=1);

namespace App\Tests\Payload;

use PHPUnit\Framework\TestCase;
use Semitexa\Core\Discovery\ClassDiscovery;
use Semitexa\Testing\Attributes\TestablePayload;
use Semitexa\Testing\Traits\TestsPayloads;

/**
 * Universal Contract Test: Automatically discovers and verifies ALL payloads
 * in the project and its packages that have the #[TestablePayload] attribute.
 *
 * Generated by: bin/semitexa test:init
 */
class ProjectPayloadsContractTest extends TestCase
{
    use TestsPayloads;

    /**
     * @dataProvider provideTestablePayloads
     * @param class-string $payloadClass
     */
    public function test_payload_follows_contract(string $payloadClass): void
    {
        $this->assertPayloadContract($payloadClass);
    }

    /**
     * @return iterable<string, array{0: class-string}>
     */
    public static function provideTestablePayloads(): iterable
    {
        ClassDiscovery::initialize();
        $payloads = ClassDiscovery::findClassesWithAttribute(TestablePayload::class);

        foreach ($payloads as $class) {
            $shortName = (new \ReflectionClass($class))->getShortName();
            yield $shortName . ' (' . $class . ')' => [$class];
        }
    }
}

PHP;
}
